version: '3.9'

services:
  city-api-prod:
    container_name: city-api-prod
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:prod
    environment:
      NODE_ENV: production
      PORT: 3000
